AWSTemplateFormatVersion: '2010-09-09'

Resources:
    LambdaFunction:
        Type: AWS::Lambda::Function
        Properties:
            FunctionName: cfn-test
            Handler: "lambda.lambda_handler"
            Runtime: python3.6
            Timeout: 10
            Role:
                !GetAtt LambdaRole.Arn
            Code:
                S3Bucket: daleksprinter
                S3Key: lambda.zip
            Tags:
                - Key: Name
                  Value: cfn-test

    LambdaRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: 
                Version: '2012-10-17'
                Statement: 
                  - 
                    Effect: Allow
                    Principal: 
                        Service: 
                            - lambda.amazonaws.com
                    Action: 
                        - sts:AssumeRole
